# Generated by Django 2.1.1 on 2018-09-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20180928_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='description',
        ),
        migrations.AddField(
            model_name='drone',
            name='brand',
            field=models.CharField(choices=[('DJI', 'DJI'), ('PHANTOM', 'PHANTOM'), ('x4303', 'x4303')], default=2, max_length=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drone',
            name='serial_number',
            field=models.TextField(default=33, max_length=120),
            preserve_default=False,
        ),
    ]
