# Generated by Django 2.1.1 on 2018-09-28 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20180928_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='associated_camera',
            field=models.IntegerField(default=222),
            preserve_default=False,
        ),
    ]
